M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date sáb 25 feb 2023 16:44:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-25T16:44:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.500
%
G90
G05
T1
X154.3Y-176.3
T2
X156.8Y-104.0
T3
X123.75Y-127.75
T0
M30
